FROM python:alpine
ENV PYTHONUNBUFFERED=1
RUN pip install Flask
RUN pip install google-api-python-client
RUN pip install google-auth-httplib2
RUN pip install google-auth-oauthlib
RUN pip install parse
