version: '3.8'
services:
  flask:
    build: ./docker/flask
    ports: 
      - 9000:80
    volumes:
      - ./app:/workspace
    working_dir: /workspace
    command: python server.py
  nuxt:
    build: ./docker/nuxt
    ports:
      - 4000:3000
    volumes:
      - ./nuxt_app:/workspace
    working_dir: /workspace
    command: yarn run dev
    